### ISSUE TITLE
First revision

### ISSUE THREAD

**Issue by caprenter** [OpenDataServices/developer-docs#1]
@Bjwebb I'd appreciate it if you could take some time to check this first set of documents over.

There is some rst to md tidying up to do, which I think you could do quickly, but the content (text) also needs a bit of a check, but only a little needs re-writes I hope.

**Comment by Bjwebb** [comment]
I think I've made all the required formatting changes.

On the whole the content is good. I think the biggest task going forward is to flesh this out more, and also make sure we use it! (particularly the code checklist).

I've added some issues for some specific points. The only really incorrect piece is the Python page - https://github.com/OpenDataServices/developer-docs/issues/4 - which I've assigned to myself to update.
