### ISSUE TITLE
Our code should be public

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/developer-docs#10]
... and our development processes should be public.

This is implied throughout https://github.com/OpenDataServices/developer-docs/blob/master/code.md and there's some mention of public workplans https://github.com/OpenDataServices/developer-docs/blob/master/code.md#workplans , but I think maybe we could be more explicit. (e.g. saying the code should be in the GitHub organisation implies public, but private repos in that organisation are possible).

**Comment by Bjwebb** [comment]
@caprenter Should this also be in the code checklist?

**Comment by caprenter** [comment]
That's as a good a place as any. Yes.
