### ISSUE TITLE
The lead for a project, should be the one to merge pull requests?

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/developer-docs#14]
We should have a lead person identified - https://github.com/OpenDataServices/developer-docs/blob/master/code-checklist.md#2-all-code-should-have-a-lead-person-identified

Should they responsible for merges etc.? This responsibility may be delegated, but it might be good to have a default that they are the only one to push to master/live?

**Comment by caprenter** [comment]
yes I think that is a good point
