### ISSUE TITLE
General approaches to software development

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/developer-docs#21]
We may want to add some information about this, e.g.:
* https://en.wikipedia.org/wiki/Technical_debt
* 12 factor web apps
* DRY, and similarly having a SSOT

Other possibilities / aspirations:
* Agile

**Comment by caprenter** [comment]
Also add something about README driven development

**Comment by caprenter** [comment]
I think this issue can be closed, and re-opened if people really want
