### ISSUE TITLE
Should we use GitHub's protected branches?

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/developer-docs#26]
I currently have this set up for Cove - for the branches `master` and `live`.

It's not possible to push directly to the branch - tests must pass on Travis before code can go in. If you try you get:
```
! [remote rejected] master -> master (protected branch hook declined)
```
Fastforward merges into master of commits that have already passed - it's not necessary to use GitHub's merge interfaces.

I think it would be good to set this up for *all* our live branches, and most of our master branches on our code repositories.

**Comment by caprenter** [comment]
Yes I think this is a good idea. What does @timgdavies think?

**Comment by timgdavies** [comment]
I think this would definitely protect you from me ;) 

Um - yes - a good idea.
