### ISSUE TITLE
Default Huboard columns changes

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/developer-docs#43]
I've just set this up for developer-docs and it looks like the initial defaults have changed - https://huboard.com/OpenDataServices/developer-docs/

Looks like there's now a Review column, and sort of limit on how many issues can be "Working". We may want to evaluate this, and decide whether to set it up for other projects.

We might also want to think about what other column changes we want to make, as I think it's all very configurable.

**Comment by odscjames** [comment]
I've not heard mention of this, is this still used? Can take out section totally if not.

**Comment by robredpath** [comment]
Yeah, this has been superceded by GitHub Projects.
