### ISSUE TITLE
Version control checklist item is not numbered

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/developer-docs#6]
https://github.com/OpenDataServices/developer-docs/blob/master/code-checklist.md#our-codeprojects-should-be-in-version-control-and-present-links-to-issue-trackers-and-source-code

I'm not sure if this should be at the bottom, or whether we want to bump all the numbers below this?

**Comment by caprenter** [comment]
Ah - yes that's a mistake.

I'm actually not bothered about order here (maybe we should be tho?). I'll fix it first, and then if we are concerned about order we can change that later.
