### ISSUE TITLE
Is GitBooks broken?

### ISSUE THREAD

**Issue by odscjames** [OpenDataServices/developer-docs#67]
https://github.com/OpenDataServices/developer-docs/blob/master/code-python.md does NOT match https://opendataservices.gitbooks.io/developer-docs/content/code-python.html 

Is our GitBooks broken?

**Comment by odscjames** [comment]
Why would they NOT update/redirect the old ones??? Anything we can do to kill the old ones to avoid confusion?

Thanks anyway. I'll update the Readme quickly.

**Comment by robredpath** [comment]
I've not had any involvement in our GitBooks setup so assigning @Bjwebb :)

**Comment by Bjwebb** [comment]
Looks like I can redirect the old site to https://opendataservices.gitbook.io/developer-docs

**Comment by odscjames** [comment]
Thanks @Bjwebb !
