### ISSUE TITLE
Converse of adapting with external changes

### ISSUE THREAD

**Issue by Bjwebb** [OpenDataServices/developer-docs#7]
https://github.com/OpenDataServices/developer-docs/blob/master/code-checklist.md#10-our-code-will-need-to-adapt-with-schema-changes-and-changes-to-external-systems-upon-which-it-relies

Reading this, it occured to me we might want to consider the opposite of this - that we might be providing APIs on which others rely, and we want to be careful to give people sufficient warning of changes etc.

**Comment by caprenter** [comment]
Item 13 in the checklist is meant to cover this  - we should be able to communicate with our users

**Comment by Bjwebb** [comment]
Yes, you're right. I might try adding a note about APIs to this Item.
